# Generated by Django 4.1.1 on 2022-11-05 13:54

# django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Doctor'), (3, 'Patient')], default=3),
        ),
    ]
