# Generated by Django 4.1.1 on 2022-09-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Slot",
                "verbose_name_plural": "Slots",
            },
        ),
    ]
