# Generated by Django 4.1.1 on 2022-09-20 19:42

# django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="name",
            field=models.CharField(default="name", max_length=50),
        ),
    ]
