# Generated by Django 4.1.1 on 2022-09-20 19:53

# django
import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="slot",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
